import type { Roommate, Expense } from '@/types/expense';

export const ROOMMATES: Roommate[] = [
  { id: 'ali', name: 'Ali', color: 'bg-blue-500' },
  { id: 'lukas', name: 'Lukas', color: 'bg-emerald-500' },
  { id: 'sophie', name: 'Sophie', color: 'bg-violet-500' },
  { id: 'jonas', name: 'Jonas', color: 'bg-amber-500' },
];

export const SEED_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    title: 'Miete März',
    amount: 1200.0,
    category: 'Utilities',
    paidById: 'ali',
    date: '2026-03-01',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-002',
    title: 'Supermarkt',
    amount: 87.45,
    category: 'Groceries',
    paidById: 'sophie',
    date: '2026-03-03',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-003',
    title: 'Strom & Internet',
    amount: 95.0,
    category: 'Utilities',
    paidById: 'lukas',
    date: '2026-03-05',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-004',
    title: 'Kaffee & Tee',
    amount: 24.9,
    category: 'Drinks',
    paidById: 'jonas',
    date: '2026-03-08',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-005',
    title: 'Reinigungsmittel',
    amount: 32.8,
    category: 'Household',
    paidById: 'sophie',
    date: '2026-03-10',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-006',
    title: 'Kühlschrank-Reparatur',
    amount: 145.0,
    category: 'Repairs',
    paidById: 'ali',
    date: '2026-03-12',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-007',
    title: 'Bier & Snacks',
    amount: 42.5,
    category: 'Drinks',
    paidById: 'lukas',
    date: '2026-03-15',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-008',
    title: 'Wochenmarkt',
    amount: 56.3,
    category: 'Groceries',
    paidById: 'jonas',
    date: '2026-03-18',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-009',
    title: 'Toilettenpapier & Seife',
    amount: 18.75,
    category: 'Household',
    paidById: 'ali',
    date: '2026-03-20',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
  {
    id: 'exp-010',
    title: 'Gas & Heizung',
    amount: 110.0,
    category: 'Utilities',
    paidById: 'sophie',
    date: '2026-03-22',
    splitWith: ['ali', 'lukas', 'sophie', 'jonas'],
  },
];
